{
 "title": "Centric",
 "time": { "from": "2019-01-18T00:00:00.000Z", "to": "2023-10-16T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "team",
    "label": "engineering team",
    "query": "SELECT  id AS __value ,name AS __text FROM  centric.engineering"
   }
  ]
 },
 "panels": [
  {
   "title": "Trend Repos without Renovate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select rec_date, repos_without_renovate from centric.perspectives where team_id = 103;"
    }
   ]
  },
  {
   "title": "Combined State (Latest)",
   "type": "table",
   "description": "Latest recorded values",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select e.name as \"Engineering Team\", \ncs.delivery_lead_time as \"Delivery Lead Time (hrs)\", \ncs.change_lead_rate as \"Change Lead Time (mins)\", \ncs.change_failure as \"Change Failure Rate (%)\", \ncs.mttr as \"Mean Time To Recovery (hrs)\"\nfrom centric.combined_state cs, centric.engineering e \nwhere team_id IN (${team:raw} ) and cs.team_id = e.id \norder by e.name asc"
    }
   ]
  },
  {
   "title": "Delivery Lead Time (hours)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "centric",
     "rawSql": "-- SELECT name FROM centric.engineering LIMIT 50 \nselect d.rec_date, d.delivery_lead_time, e.name from centric.delivery d, centric.engineering e where d.team_id = e.id and d.team_id IN ($team ) "
    }
   ]
  },
  {
   "title": "Change Failure Rate (percentage)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 28 },
   "targets": [
    {
     "dataset": "centric",
     "rawSql": "-- SELECT name FROM centric.engineering LIMIT 50 \nselect f.rec_date, f.change_failure, e.name from centric.change_failure_rate f, centric.engineering e where f.team_id = e.id and f.team_id IN ($team) "
    }
   ]
  },
  {
   "title": "Change Lead Rate (minutes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 38 },
   "targets": [
    {
     "dataset": "centric",
     "rawSql": "-- SELECT name FROM centric.engineering LIMIT 50 \nselect m.rec_date, m.change_lead_rate, e.name from centric.change_lead_rate m, centric.engineering e where m.team_id = e.id and m.team_id IN ($team) "
    }
   ]
  },
  {
   "title": "Mean Time To Recovery (hours)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 48 },
   "targets": [
    {
     "dataset": "centric",
     "rawSql": "-- SELECT name FROM centric.engineering LIMIT 50 \nselect m.rec_date, m.mttr, e.name from centric.mean_time_to_recovery m, centric.engineering e where m.team_id = e.id and m.team_id IN ($team) "
    }
   ]
  },
  {
   "title": "Aggregated View (OLDE)",
   "type": "table",
   "description": "Delivery, change failure, change lead and recovery",
   "gridPos": { "h": 7, "w": 12, "x": 1, "y": 58 },
   "targets": [
    {
     "dataset": "centric",
     "rawSql": "select e.name,  d.delivery_lead_time\n    from centric.delivery d, centric.engineering e\n    where d.team_id = e.id and e.id IN ($team )\n    order by rec_date desc limit 3\n"
    },
    {
     "rawSql": "select e.name, cfr.change_failure\n    from centric.change_failure_rate cfr, centric.engineering e\n    where cfr.team_id = e.id and e.id in ($team )\n    order by rec_date desc limit 3;"
    },
    {
     "rawSql": "select e.name, clr.change_lead_rate\n    from centric.change_lead_rate clr, centric.engineering e\n    where clr.team_id = e.id and e.id in ($team)\n    order by rec_date desc limit 3;"
    },
    {
     "rawSql": "select e.name, m.mttr\n    from centric.mean_time_to_recovery m, centric.engineering e\n    where m.team_id = e.id and e.id in ($team)\n    order by rec_date desc limit 3;\n"
    }
   ]
  }
 ]
}