{
 "title": "FIXED PERSPECTIVE",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "team_id", "label": "Engineering Team", "query": "103" }
  ]
 },
 "panels": [
  {
   "title": "Engineering Team Name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select name from centric.engineering where id = $team_id "
    }
   ]
  },
  {
   "title": "Code Smells per Repository",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select rec_date, code_smells_per_repo from centric.perspectives where team_id = $team_id "
    }
   ]
  },
  {
   "title": "Repos without Renovate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select rec_date, repos_without_renovate from centric.perspectives where team_id = $team_id"
    }
   ]
  },
  {
   "title": "Complexity (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select rec_date, complexity from centric.perspectives where team_id = $team_id "
    }
   ]
  },
  {
   "title": "Coverage (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select rec_date, coverage from centric.perspectives where team_id = $team_id "
    }
   ]
  },
  {
   "title": "Deprecated Helm Charts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select rec_date, deprecated_helm_charts from centric.perspectives where team_id = $team_id "
    }
   ]
  }
 ]
}